#!/usr/bin/env sh
set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
REPO_ROOT=$(CDPATH= cd -- "$SCRIPT_DIR/../.." && pwd)
: "${ROOT_DIR:=$REPO_ROOT/consumer/hyprland-plugin}"
PLUGIN_SRC_DIR="${PLUGIN_SRC_DIR:-$ROOT_DIR}"
VIVID_HYPRLAND_PLUGIN_BUILD_ROOT="${VIVID_HYPRLAND_PLUGIN_BUILD_ROOT:-$PLUGIN_SRC_DIR/.build}"
PLUGIN_BUILD_DIR="${PLUGIN_BUILD_DIR:-$VIVID_HYPRLAND_PLUGIN_BUILD_ROOT}"
PLUGIN_INSTALL_PREFIX="${VIVID_HYPRLAND_PLUGIN_PREFIX:-$HOME/.local}"
PLUGIN_INSTALL_DIR="${PLUGIN_INSTALL_DIR:-$PLUGIN_INSTALL_PREFIX/lib/vivid/hyprland}"

export REPO_ROOT PLUGIN_SRC_DIR VIVID_HYPRLAND_PLUGIN_BUILD_ROOT PLUGIN_BUILD_DIR PLUGIN_INSTALL_PREFIX PLUGIN_INSTALL_DIR
